name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 10
        platform: x64
        
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 10
        platform: x64
        
    - name: install-preq
      run: |
           sudo apt install mpi-default-dev ninja-build libomp-dev
           pip install gcovr


    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
            cmake --preset=coverage .
            cmake --preset=release-gnu .
            cmake --preset=release-clang .



    - name: Build
      # Build your program with the given configuration
      run: |
            cmake --build --preset=coverage --target UnitTest -j 2
            cmake --build --preset=release-gnu --target PerformanceTesting -j 2
            cmake --build --preset=release-clang --target PerformanceTesting -j 2
      
    - name: test
      working-directory: ${{github.workspace}}/build/coverage/UnitTest/
      run: | 
           ./UnitTest --gtest_output="xml:report.xml"
           gcovr --txt -r ${{github.workspace}} --filter ${{github.workspace}}/include/ --coveralls=${{github.workspace}}/coverage.json --fail-under-line 90
           cd ${{github.workspace}}
           ls
           
    - name: performance
      working-directory: ${{github.workspace}}/build/coverage/perf/
      run: | 
           ./PerformanceTesting"
           ls -larth
      
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
       files:  ${{github.workspace}}/build/coverage/UnitTest/report.xml
       
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{github.workspace}}


   # - name: Test
   #   working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
      
